# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [1]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode == 'zeros':
        return np.zeros(shape)
    elif mode == 'ones':
        return np.ones(shape)
    elif mode == 'full':
        return np.full(shape, value)
    elif mode == 'identity':
        return np.eye(shape)
    else:
        raise ValueError("Unknown mode. Choose from 'zeros', 'ones', 'full', 'identity'.")

Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [2]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = arr1.reshape(new_shape)

        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")

part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [3]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (greater than or equal to the threshold)
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array (ndarray)
    arr = np.array(arr)

    # 2. Define the condition with an elementwise comparison (Boolean array)
    condition = np.greater_equal(arr, threshold)

    # 3. Apply modification using np.where(condition, value_if_true, value_if_false)
    modified_arr = np.where(condition, replacement_value, arr)

    return modified_arr

TestCase

In [4]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6]

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9],
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B, then apply threshold
combined = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
final_report = apply_threshold(combined, 12, -99)
print(final_report)

[[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11 -99]]


In [5]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])